from __future__ import annotations

import pathlib
import typing
from itertools import batched

CURRENT_PATH: typing.Final[pathlib.Path] = pathlib.Path(__file__).resolve()
REPO_ROOT: typing.Final[pathlib.Path] = CURRENT_PATH.parent.parent.parent
CURRENT_RELATIVE_PATH: typing.Final[pathlib.Path] = CURRENT_PATH.relative_to(REPO_ROOT)
# Base32768
BASE_32768_PATH: typing.Final[pathlib.Path] = REPO_ROOT / "src" / "radixly" / "base32768" / "_tables.h"
BASE_32768_BITS_PER_CHAR: typing.Final = 15
BASE_32768_BITS_PER_BYTE: typing.Final = 8
# alphabet data copied from qntm's base32768 (github.com/qntm/base32768), MIT licensed, copyright qntm.
BASE_32768_PAIR_STRINGS: typing.Final[tuple[str, ...]] = (
    "ҠҿԀԟڀڿݠޟ߀ߟကဟႠႿᄀᅟᆀᆟᇠሿበቿዠዿጠጿᎠᏟᐠᙟᚠᛟកសᠠᡟᣀᣟᦀᦟ᧠᧿ᨠᨿᯀᯟᰀᰟᴀᴟ⇠⇿⋀⋟⍀⏟␀␟─❟➀➿⠀⥿⦠⦿⨠⩟⪀⪿⫠⭟ⰀⰟⲀⳟⴀⴟⵀⵟ⺠⻟㇀㇟㐀䶟䷀龿ꀀꑿ꒠꒿ꔀꗿꙀꙟꚠꛟ꜀ꝟꞀꞟꡀꡟ",
    "ƀƟɀʟ",
)


class IndentWriter:
    """Indent writer used for dynamically generate files."""

    def __init__(self, file_path: pathlib.Path, *, indent_char: str = " ", indent_amount: int = 4) -> None:
        """Construct a new indent writer object."""
        self.file_path: pathlib.Path = file_path
        self.lines: list[tuple[str, int]] = []
        self.indent_char: str = indent_char
        self.indent_amount: int = indent_amount

    def write_line(self, text: str, indent_depth: int = 0) -> None:
        """Write a line with a new line character at the end to the buffer."""
        self.lines.append((text + "\n", indent_depth))

    def write_blank(self) -> None:
        """Write a blank empty line to the buffer."""
        self.lines.append(("\n", 0))

    def write_file(self) -> None:
        """Write content to file."""
        with self.file_path.open("w", encoding="utf-8") as file:
            for line in self.lines:
                indent: str = (self.indent_char * self.indent_amount) * line[1]
                file.write(indent + line[0])


def _build_base32768_tables() -> dict[int, tuple[int, ...]]:
    lookup_e: dict[int, tuple[int, ...]] = {}

    for r, pair_string in enumerate(BASE_32768_PAIR_STRINGS):
        repertoire: list[int] = []
        for i in range(0, len(pair_string), 2):
            first, last = ord(pair_string[i]), ord(pair_string[i + 1])
            repertoire.extend(cp for cp in range(first, last + 1))

        num_z_bits = BASE_32768_BITS_PER_CHAR - BASE_32768_BITS_PER_BYTE * r
        lookup_e[num_z_bits] = tuple(repertoire)

    _verify_base32768_tables(lookup_e)
    return lookup_e


def _verify_base32768_tables(lookup_e: dict[int, tuple[int, ...]]) -> None:
    overlap = set(lookup_e[BASE_32768_BITS_PER_CHAR]) & set(lookup_e[BASE_32768_BITS_PER_CHAR - 8])
    assert len(overlap) == 0, f"repertoires overlap: {sorted(hex(cp) for cp in overlap)}"

    assert len(lookup_e[BASE_32768_BITS_PER_CHAR]) == 32768, (
        f"15-bit repertoire has {len(lookup_e[BASE_32768_BITS_PER_CHAR])} code points, expected 32768"
    )
    assert len(lookup_e[BASE_32768_BITS_PER_CHAR]) == len(set(lookup_e[BASE_32768_BITS_PER_CHAR])), (
        f"15-bit repertoire contains {32768 - len(set(lookup_e[BASE_32768_BITS_PER_CHAR]))} duplicate code points"
    )

    assert len(lookup_e[BASE_32768_BITS_PER_CHAR - 8]) == 128, (
        f"7-bit repertoire has {len(lookup_e[BASE_32768_BITS_PER_CHAR - 8])} code points, expected 128"
    )
    assert len(lookup_e[BASE_32768_BITS_PER_CHAR - 8]) == len(set(lookup_e[BASE_32768_BITS_PER_CHAR - 8])), (
        f"7-bit repertoire contains {128 - len(set(lookup_e[BASE_32768_BITS_PER_CHAR - 8]))} duplicate code points"
    )
    for codepoints in lookup_e.values():
        for cp in codepoints:
            assert cp <= 0xFFFF, f"code point U+{cp:04X} outside uint16/canonical range [0x100, 0xFFFF]"
            assert cp >= 0x100, f"code point U+{cp:04X} outside uint16/canonical range [0x100, 0xFFFF]"


def write_base_32768_table() -> None:

    lookup_e = _build_base32768_tables()

    writer = IndentWriter(BASE_32768_PATH)
    writer.write_line("//")
    writer.write_line(f"// Auto generated by {CURRENT_RELATIVE_PATH}")
    writer.write_line(
        "// Alphabet data copied from qntm's base32768 (github.com/qntm/base32768), MIT licensed, copyright qntm."
    )
    writer.write_line("//")
    writer.write_line("#ifndef RADIXLY_BASE32768_TABLES_H")
    writer.write_line("#define RADIXLY_BASE32768_TABLES_H")
    writer.write_line("#include <stdint.h>")
    writer.write_blank()

    writer.write_line("static const uint16_t RADIXLY_B32768_FWD15[32768] = {")
    for chunk in batched(lookup_e[BASE_32768_BITS_PER_CHAR], 14):
        writer.write_line(", ".join(f"0x{cp:04X}" for cp in chunk) + ",", indent_depth=1)
    writer.write_line("};")
    writer.write_blank()

    writer.write_line("static const uint16_t RADIXLY_B32768_FWD7[128] = {")
    for chunk in batched(lookup_e[BASE_32768_BITS_PER_CHAR - 8], 14):
        writer.write_line(", ".join(f"0x{cp:04X}" for cp in chunk) + ",", indent_depth=1)
    writer.write_line("};")
    writer.write_blank()

    writer.write_line("#endif")
    writer.write_file()


if __name__ == "__main__":
    write_base_32768_table()
