"""Conformance and differential tests for the C base32768 encoder."""

import inspect
import random
from pathlib import Path

import pytest
from hypothesis import given
from hypothesis import strategies as st
from reference.base32768 import encode as reference_encode

from radixly._core import base32768_encode

# Seeded, not os.urandom: when a length fails in CI, the exact payload can be
# regenerated byte-for-byte, locally, forever. Zeros and ones flank the random
# flavor: all-zeros hits FWD15[0] and the all-zero tail, all-ones the mirror.
PAYLOAD_FLAVORS = {
    "random": lambda n: random.Random(n).randbytes(n),
    "zeros": lambda n: bytes(n),
    "ones": lambda n: b"\xff" * n,
}


def test_encode_conformance(bin_path: Path) -> None:
    payload = bin_path.read_bytes()
    expected = bin_path.with_suffix(".txt").read_text(encoding="utf-8")
    assert base32768_encode(payload) == expected


@pytest.mark.parametrize("n", range(601))
@pytest.mark.parametrize("flavor", PAYLOAD_FLAVORS)
def test_encode_matches_reference_every_length(flavor: str, n: int) -> None:
    """Every tail shape (0..14 leftover bits) at every small length, both ways
    through the 8-vs-15 cycle -- wrong length math or a broken tail can't hide
    between sampled lengths."""
    payload = PAYLOAD_FLAVORS[flavor](n)
    assert base32768_encode(payload) == reference_encode(payload)


@given(st.binary())
def test_encode_matches_reference(payload: bytes) -> None:
    assert base32768_encode(payload) == reference_encode(payload)


def test_encode_matches_reference_megabyte() -> None:
    """MB-scale differential: the vectors top out at 128 KiB, and size-dependent
    bugs (output-length math, allocation) only surface past their comfort zone."""
    payload = random.Random(2**20).randbytes(2**20)
    assert base32768_encode(payload) == reference_encode(payload)


@pytest.mark.parametrize("bad", ["text", 42], ids=["str", "int"])
def test_encode_rejects_non_buffer(bad: object) -> None:
    """str input is the charter's explicit TypeError; the exact prose is the
    platform's, so match only the load-bearing phrase."""
    with pytest.raises(TypeError, match="bytes-like"):
        base32768_encode(bad)


def test_signature_is_pinned() -> None:
    """Fails if the text-signature block in the C docstring is mangled or lost."""
    assert str(inspect.signature(base32768_encode)) == "(data, /)"
