"""Conformance and differential tests for the C base32768 encoder."""

from __future__ import annotations

import inspect
import random
import typing

if typing.TYPE_CHECKING:
    import pathlib
    from collections.abc import Callable

    from _typeshed import ReadableBuffer

import pytest
from hypothesis import given
from hypothesis import strategies as st
from reference.base32768 import encode as reference_encode

from radixly._core import base32768_encode


# Seeded, not os.urandom: when a length fails in CI, the exact payload can be
# regenerated byte-for-byte, locally, forever. Zeros and ones flank the random
# flavor: all-zeros hits FWD15[0] and the all-zero tail, all-ones the mirror.
def _random_payload(n: int) -> bytes:
    return random.Random(n).randbytes(n)


def _ones_payload(n: int) -> bytes:
    return b"\xff" * n


PAYLOAD_FLAVORS: dict[str, Callable[[int], bytes]] = {
    "random": _random_payload,
    "zeros": bytes,
    "ones": _ones_payload,
}


def test_encode_conformance(base32768_bin_path: pathlib.Path) -> None:
    payload = base32768_bin_path.read_bytes()
    expected = base32768_bin_path.with_suffix(".txt").read_text(encoding="utf-8")
    assert base32768_encode(payload) == expected


@pytest.mark.parametrize("n", range(601))
@pytest.mark.parametrize("flavor", PAYLOAD_FLAVORS)
def test_encode_matches_reference_every_length(flavor: str, n: int) -> None:
    """Every tail shape (0..14 leftover bits) at every small length, both ways
    through the 8-vs-15 cycle -- wrong length math or a broken tail can't hide
    between sampled lengths."""
    payload = PAYLOAD_FLAVORS[flavor](n)
    assert base32768_encode(payload) == reference_encode(payload)


@given(st.binary())
def test_encode_matches_reference(payload: bytes) -> None:
    assert base32768_encode(payload) == reference_encode(payload)


@pytest.mark.parametrize("view", [bytes, bytearray, memoryview])
def test_encode_accepts_any_buffer(view: Callable[[bytes], ReadableBuffer]) -> None:
    """The charter: encode() accepts any buffer-protocol object, not just bytes."""
    payload = random.Random(99).randbytes(187)
    assert base32768_encode(view(payload)) == base32768_encode(payload)


def test_encode_matches_reference_megabyte() -> None:
    """MB-scale differential: the vectors top out at 128 KiB, and size-dependent
    bugs (output-length math, allocation) only surface past their comfort zone."""
    payload = random.Random(2**20).randbytes(2**20)
    assert base32768_encode(payload) == reference_encode(payload)


@pytest.mark.parametrize("bad", ["text", 42], ids=["str", "int"])
def test_encode_rejects_non_buffer(bad: str | int) -> None:
    """str input is the charter's explicit TypeError; the exact prose is the
    platform's, so match only the load-bearing phrase."""
    with pytest.raises(TypeError, match="bytes-like"):
        base32768_encode(bad)  # pyright: ignore[reportArgumentType]


def test_signature_is_pinned() -> None:
    """Fails if the text-signature block in the C docstring is mangled or lost."""
    assert str(inspect.signature(base32768_encode)) == "(data, /)"
