from typing import Final

from _typeshed import ReadableBuffer
from typing_extensions import override

COMPILER: Final[str]
OPTIMIZED: Final[bool]

class DecodeError(ValueError):
    def __init__(self, position: int, *, message: str | None = None) -> None: ...
    @override
    def __reduce__(self) -> tuple[type[DecodeError], tuple[int], str | None]: ...
    # State is deliberately narrower than BaseException's dict-or-None: the
    # pickle channel carries only the message; anything else is rejected.
    @override
    def __setstate__(self, state: str) -> None: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @property
    def position(self) -> int: ...
    @property
    def message(self) -> str | None: ...

def base32768_encode(data: ReadableBuffer, /) -> str: ...
def base32768_decode(data: str, /) -> bytes: ...
def braille_encode(data: ReadableBuffer, /) -> str: ...
def braille_decode(data: str, /) -> bytes: ...
def hexagram_encode(data: ReadableBuffer, /) -> str: ...
def hexagram_decode(data: str, /) -> bytes: ...
def uro14_encode(data: ReadableBuffer, /) -> str: ...
def uro14_decode(data: str, /) -> bytes: ...
