# Copyright (c) 2026-present rayakame
from typing import Final

from _typeshed import ReadableBuffer
from typing_extensions import override

COMPILER: Final[str]
OPTIMIZED: Final[bool]

class DecodeError(ValueError):
    def __init__(self, position: int, *, message: str | None = None) -> None: ...
    @override
    def __reduce__(self) -> tuple[type[DecodeError], tuple[int], str | None]: ...
    # State is deliberately narrower than BaseException's dict-or-None: the
    # pickle channel carries only the message; anything else is rejected.
    @override
    def __setstate__(self, state: str) -> None: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @property
    def position(self) -> int: ...
    @property
    def message(self) -> str | None: ...

def base16_encode(data: ReadableBuffer, /) -> str: ...
def base16_decode(data: str, /) -> bytes: ...
def base2048_encode(data: ReadableBuffer, /) -> str: ...
def base2048_decode(data: str, /) -> bytes: ...
def base32_encode(data: ReadableBuffer, /) -> str: ...
def base32_decode(data: str, /) -> bytes: ...
def base32768_encode(data: ReadableBuffer, /) -> str: ...
def base32768_decode(data: str, /) -> bytes: ...
def base32hex_encode(data: ReadableBuffer, /) -> str: ...
def base32hex_decode(data: str, /) -> bytes: ...
def base65536_encode(data: ReadableBuffer, /) -> str: ...
def base65536_decode(data: str, /) -> bytes: ...
def braille_encode(data: ReadableBuffer, /) -> str: ...
def braille_decode(data: str, /) -> bytes: ...
def hexagram_encode(data: ReadableBuffer, /) -> str: ...
def hexagram_decode(data: str, /) -> bytes: ...
def uro14_encode(data: ReadableBuffer, /) -> str: ...
def uro14_decode(data: str, /) -> bytes: ...

# The stdlib base64 drop-in, typed as typeshed types the originals.
def b16encode(s: ReadableBuffer) -> bytes: ...
def b16decode(s: str | ReadableBuffer, casefold: bool = False) -> bytes: ...
def b32encode(s: ReadableBuffer) -> bytes: ...
def b32decode(s: str | ReadableBuffer, casefold: bool = False, map01: str | ReadableBuffer | None = None) -> bytes: ...
def b32hexencode(s: ReadableBuffer) -> bytes: ...
def b32hexdecode(s: str | ReadableBuffer, casefold: bool = False) -> bytes: ...
