# Copyright (c) 2026-present rayakame
from typing import Final

from _typeshed import ReadableBuffer
from typing_extensions import override

COMPILER: Final[str]
OPTIMIZED: Final[bool]

class DecodeError(ValueError):
    def __init__(self, position: int, *, message: str | None = None) -> None: ...
    @override
    def __reduce__(self) -> tuple[type[DecodeError], tuple[int], str | None]: ...
    # State is deliberately narrower than BaseException's dict-or-None: the
    # pickle channel carries only the message; anything else is rejected.
    @override
    def __setstate__(self, state: str) -> None: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @property
    def position(self) -> int: ...
    @property
    def message(self) -> str | None: ...

def base16_encode(data: ReadableBuffer, /) -> str: ...
def base16_decode(data: str, /) -> bytes: ...
def base2048_encode(data: ReadableBuffer, /) -> str: ...
def base2048_decode(data: str, /) -> bytes: ...
def base32_encode(data: ReadableBuffer, /) -> str: ...
def base32_decode(data: str, /) -> bytes: ...
def base32768_encode(data: ReadableBuffer, /) -> str: ...
def base32768_decode(data: str, /) -> bytes: ...
def base32hex_encode(data: ReadableBuffer, /) -> str: ...
def base32hex_decode(data: str, /) -> bytes: ...
def base64_encode(data: ReadableBuffer, /) -> str: ...
def base64_decode(data: str, /) -> bytes: ...
def base64url_encode(data: ReadableBuffer, /) -> str: ...
def base64url_decode(data: str, /) -> bytes: ...
def base65536_encode(data: ReadableBuffer, /) -> str: ...
def base65536_decode(data: str, /) -> bytes: ...
def braille_encode(data: ReadableBuffer, /) -> str: ...
def braille_decode(data: str, /) -> bytes: ...
def hexagram_encode(data: ReadableBuffer, /) -> str: ...
def hexagram_decode(data: str, /) -> bytes: ...
def uro14_encode(data: ReadableBuffer, /) -> str: ...
def uro14_decode(data: str, /) -> bytes: ...

# The stdlib base64 drop-in, typed as typeshed types the originals.
def b16encode(s: ReadableBuffer) -> bytes: ...
def b16decode(s: str | ReadableBuffer, casefold: bool = False) -> bytes: ...
def b32encode(s: ReadableBuffer) -> bytes: ...
def b32decode(s: str | ReadableBuffer, casefold: bool = False, map01: str | ReadableBuffer | None = None) -> bytes: ...
def b32hexencode(s: ReadableBuffer) -> bytes: ...
def b32hexdecode(s: str | ReadableBuffer, casefold: bool = False) -> bytes: ...
def b64encode(s: ReadableBuffer, altchars: ReadableBuffer | None = None) -> bytes: ...
def b64decode(
    s: str | ReadableBuffer, altchars: str | ReadableBuffer | None = None, validate: bool = False
) -> bytes: ...
def standard_b64encode(s: ReadableBuffer) -> bytes: ...
def standard_b64decode(s: str | ReadableBuffer) -> bytes: ...
def urlsafe_b64encode(s: ReadableBuffer) -> bytes: ...
def urlsafe_b64decode(s: str | ReadableBuffer) -> bytes: ...
def a85encode(
    b: ReadableBuffer, *, foldspaces: bool = False, wrapcol: int = 0, pad: bool = False, adobe: bool = False
) -> bytes: ...
def a85decode(
    b: str | ReadableBuffer, *, foldspaces: bool = False, adobe: bool = False, ignorechars: str | ReadableBuffer = ...
) -> bytes: ...
def b85encode(b: ReadableBuffer, pad: bool = False) -> bytes: ...
def b85decode(b: str | ReadableBuffer) -> bytes: ...
def z85encode(s: ReadableBuffer) -> bytes: ...
def z85decode(s: str | ReadableBuffer) -> bytes: ...

# Which binascii.a2b_base64 a CPython release ships, as b64decode selects it at import; for the test suite.
def a2b_base64_variant(hexversion: int, /) -> int: ...
